language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6
before_script:
  - "mkdir -p ~/.composer"
  - composer self-update
  - composer install
script:
  - vendor/bin/phpunit